[machine]
entrypoint = "/opt/cartesi/dapp/dapp"
ram_length = "256Mi"
user = "root"
workdir = "/opt/cartesi/dapp"

[drives.root]
builder = "docker"
dockerfile = "build/Dockerfile.echoApp"
format = "ext2"
